### ISSUE TITLE
Invalid auth code / password reset after 2FA login / redirects back to the login screen

### ISSUE THREAD

**Issue by Romanavr** [born05/craft-twofactorauthentication#76]
Craft Pro 4.4.6.1
Two-Factor Authentication  3.1.0
PHP version  8.1.16

I ran into some problems and it would be nice if there is any solution:

1. **Invalid auth code**: In some cases, newly registered users are unable to login to the admin panel due to an invalid code.
Even after synchronization time("Time correction for codes") in the Google Auth application, it still says that the authorization code is invalid. Any idea what it could be? Not sure if this is the problem plugin, I saw the `totpDelay` parameter, I suppose it might help?

2. **Password reset after 2FA login**: Another case. The user can log in, the authorization code is valid, but after it redirects to the CP login screen with the error about "Invalid credentials", and the previous password is no longer valid. I don't know what exactly is happening, but the password definitely changes after entering the 2FA code, because the previous one is no longer valid.

3. **Redirects back to the login**: Previously I got this issue https://github.com/born05/craft-twofactorauthentication/issues/70 and after upgrade to craft 4.x it seems happens again. I'm assuming this could be related to the second case somehow? The fix for me is the same, it's just clear the browser storage.

**Comment by roelvanhintum** [comment]
Is this fixed with ~~3.3.0~~?

Edit: 3.3.1

**Comment by Romanavr** [comment]
> Is this fixed with ~3.3.0~?
> 
> Edit: 3.3.1

I'll update plugin and let you know

**Comment by Romanavr** [comment]
@roelvanhintum 
Still doesn't work, In the inspector I can see 400 response after typing code from app.

**Comment by roelvanhintum** [comment]
@Romanavr it could be that a new code is generated. Did you rescan the QR code?

**Comment by Romanavr** [comment]
> @Romanavr it could be that a new code is generated. Did you rescan the QR code?

Of course, I re-scanned and tried with the new code, even more than once.

**Comment by Romanavr** [comment]
@roelvanhintum 
Just letting you know: the problem occurs when 2FA is not yet set up for the account.
If 2FA is already there, there is no problem with the login.

**Comment by roelvanhintum** [comment]
Lets move this to one issue #84, to hopefully faster solving the issue.
